---
### TASKS: Erase old installation

- name: stop wildfly service
  service:
    name: wildfly
    state: stopped
    enable: no

- name: delete "{{ wildfly_home }}"
  file:
    path: "{{ wildfly_home }}"
    state: absent


# vim:ft=ansible:
