---
### TASKS: Install WildFly on Debian/RedHat based linux

#- debug: var=vars
#- fail: msg="Stop it"

- name: Install prerequisites - Debian
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ windfly_debian_packages }}"
  when: ansible_os_family == 'Debian'

- name: Install prerequisites - RedHat
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ windfly_redhat_packages }}"
  when: ansible_os_family == 'RedHat'

- name: create group
  group:
    name: "{{ wildfly_group }}"
    system: yes
    state: present

- name: create user
  user:
    name: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    home: "{{ wildfly_home }}"
    comment: "Fly Wild"
    shell: "/usr/sbin/nologin"
    createhome: no
    system: yes
    state: present

- name: download
  get_url:
    dest: "{{ wildfly_download_tmp }}/{{ wildfly_download_file }}"
    url: "{{ wildfly_download }}"
#    sha256sum:

- name: unpack
  unarchive:
    dest: "{{ wildfly_base_dir }}"
    src: "{{ wildfly_download_tmp }}/{{ wildfly_download_file }}"
    creates: "{{ wildfly_home }}"
    group: "{{ wildfly_group}}"
    owner: "{{ wildfly_user }}"
    remote_src: yes

- name: create simlink in install dir
  file:
    dest: "{{ wildfly_home }}"
    src: "{{ wildfly_base_dir }}/wildfly-{{ wildfly_version }}"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    state: link

- name: create dir in /etc
  file:
    path: /etc/wildfly
    state: directory
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0755

# examples are in /opt/wildfly/docs/contrib/scripts/

- name: create config from template
  template:
    src: wildfly.conf.j2
    dest: "/etc/wildfly/wildfly.conf"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_group }}"
    mode: 0644
  notify: restart wildfly service

- name: install systemd launch.sh from template
  template:
    src: launch.sh.j2
    dest: "{{ wildfly_home }}/bin/launch.sh"
    owner: "{{ wildfly_user }}"
    group: "{{ wildfly_user }}"
    mode: 0755
  notify: restart wildfly service

- name: install system service from template
  template:
    src: wildfly.service.j2
    dest: "/etc/systemd/system/wildfly.service"
    owner: root
    group: root
    mode: 0644
  notify: restart wildfly service

- name: start the service
  service:
    name: wildfly
    state: started
    enabled: yes

- name: remove downloaded files
  file:
    path: "{{ wildfly_download_tmp }}/{{ wildfly_download_file }}"
    state: absent
  when: wildfly_remove_tmp_file





# vim:ft=ansible:
